# -*- coding: utf-8 -*-
"""Criminal_West.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vw1c7SK4PwbsXsQOVBmCkn05wzawyms7
"""

import itertools

class Symbol:
    def __init__(self, name):
        self.name = name

    def __eq__(self, other):
        return isinstance(other, Symbol) and self.name == other.name

    def __hash__(self):
        return hash(("symbol", self.name))

    def __repr__(self):
        return self.name

class Not:
    def __init__(self, operand):
        self.operand = operand

    def __eq__(self, other):
        return isinstance(other, Not) and self.operand == other.operand

    def __hash__(self):
        return hash(("not", hash(self.operand)))

    def __repr__(self):
        return f"Not({self.operand})"

def resolve(ci, cj):
    resolved = set()
    for di in ci:
        for dj in cj:
            if di == Not(dj) or Not(di) == dj:
                new_clause = (ci - {di}) | (cj - {dj})
                if new_clause:  # Solo añadir si la nueva cláusula no es vacía
                    resolved.add(frozenset(new_clause))
    return resolved

def resolution(clauses):
    new = set()
    while True:
        pairs = list(itertools.combinations(clauses, 2))
        for (ci, cj) in pairs:
            resolvents = resolve(ci, cj)
            for resolvent in resolvents:
                if resolvent not in clauses and resolvent not in new:
                    print(f"Nueva cláusula formada de {ci} y {cj}: {resolvent}")
            if frozenset() in resolvents:
                return True, "Se encontró una contradicción."
            new = new.union(resolvents)
        # Condición de salida si no se encuentran nuevas cláusulas
        if new.issubset(clauses) or not new:
            return False, "No se encontró una contradicción; se comprobó la hipótesis."
        clauses = clauses.union(new)



# Definición de cláusulas en CNF
clausulas = set([
    frozenset([Not(Symbol("American(x)")), Not(Symbol("Armas(y)")), Not(Symbol("Vende(x, y, z)")), Not(Symbol("Hostil(z)")), Symbol("Criminal(x)")]),
    frozenset([Symbol("Tiene(Nono, x)"), Symbol("Misil(x)")]),
    frozenset([Not(Symbol("Misil(x)")), Symbol("Armas(x)")]),
    frozenset([Not(Symbol("Enemigo(x, America)")), Symbol("Hostil(x)")]),
    frozenset([Symbol("American(West)")]),
    frozenset([Symbol("Enemigo(Nono, America)")]),
    frozenset([Symbol("Vende(West, x, Nono)")])
])

# Aplicar el algoritmo de resolución a las cláusulas
resultado, mensaje = resolution(clausulas)
print(mensaje)

